services:
  scheme-engine:
    build:
      context: ./backend/scheme-engine
      dockerfile: Dockerfile
    env_file:
      - ./backend/docker.env
    ports:
      - "3001:3001"
    networks:
      - civilens-net

  civilens-api:
    build:
      context: ./backend/civilens-api
      dockerfile: Dockerfile
    env_file:
      - ./backend/docker.env
    depends_on:
      - scheme-engine
    ports:
      - "8080:8080"
    networks:
      - civilens-net

  form-filling-agent:
    build:
      context: ./backend/form_filling_agent
      dockerfile: Dockerfile
    env_file:
      - ./backend/docker.env
    ports:
      - "8000:8000"
    networks:
      - civilens-net

  stt-token-service:
    build:
      context: ./backend/stt-token-service
      dockerfile: Dockerfile
    env_file:
      - ./backend/docker.env
    environment:
      FUNCTIONS_WORKER_RUNTIME: node
    ports:
      - "7071:7071"
    networks:
      - civilens-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/docker.env
    depends_on:
      - civilens-api
      - form-filling-agent
      - stt-token-service
    ports:
      - "5173:5173"
    networks:
      - civilens-net

networks:
  civilens-net:
    driver: bridge
